-- =============================================
-- ENABLE ROW LEVEL SECURITY ON ALL TABLES
-- =============================================
-- Run this in Supabase SQL Editor

-- Core user tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE captains ENABLE ROW LEVEL SECURITY;
ALTER TABLE charters ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Authentication & Security
ALTER TABLE user_2fa ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_2fa_backup_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE webauthn_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE biometric_auth_logs ENABLE ROW LEVEL SECURITY;

-- Avatar System
ALTER TABLE user_avatars ENABLE ROW LEVEL SECURITY;
ALTER TABLE avatar_shop_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_avatar_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE avatar_purchase_log ENABLE ROW LEVEL SECURITY;

-- Email System
ALTER TABLE custom_emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_aliases ENABLE ROW LEVEL SECURITY;

-- Community Features
ALTER TABLE user_catches ENABLE ROW LEVEL SECURITY;
ALTER TABLE catch_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE fish_species ENABLE ROW LEVEL SECURITY;

-- Referral System
ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_invites ENABLE ROW LEVEL SECURITY;

-- Social & Analytics
ALTER TABLE social_shares ENABLE ROW LEVEL SECURITY;

-- Captain Features
ALTER TABLE weather_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE captain_documents ENABLE ROW LEVEL SECURITY;

-- Notifications
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_notification_preferences ENABLE ROW LEVEL SECURITY;

-- Chatbot
ALTER TABLE chatbot_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE chatbot_knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE chatbot_feedback ENABLE ROW LEVEL SECURITY;

-- Marketplace
ALTER TABLE marketplace_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_messages ENABLE ROW LEVEL SECURITY;

-- Inspections
ALTER TABLE inspections ENABLE ROW LEVEL SECURITY;


-- Multi-Day Trip Planner
ALTER TABLE multi_day_trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_accommodations ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_fishing_spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_packing_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_companions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_itinerary_items ENABLE ROW LEVEL SECURITY;
